version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 3
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  open-pull-requests-limit: 3
  allow:
    - dependency-type: "development"
  ignore:
    - dependency-name: "@types*"
    - dependency-name: eslint # v9 breaks our shared config
  groups:
    jest:
      patterns:
        - "jest"
        - "ts-jest"
    lint:
      patterns:
        - "eslint*"
        - "prettier"
